<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>example</groupId><artifactId>impact-fixtures</artifactId><version>1.0-SNAPSHOT</version></parent><artifactId>runtime</artifactId><properties><impact.skip>${impact.skip.runtime}</impact.skip></properties><dependencies><dependency><groupId>org.springframework</groupId><artifactId>spring-context</artifactId><version>${spring.version}</version></dependency></dependencies></project>
